from shortCardiacBackend.CoordReader import CoordReader
from shortCardiacBackend.Config import RunConfiguration
from shortCardiacBackend.ShortCardiac import ShortCardiac
from shortCardiacBackend.supportFunction import parse_to_arguments
from shortCardiacBackend.loadAndSave import load_DICOMs, save, generate_mp4